#!/bin/bash -e

# jenkins host uid/gid
jenkins_uid=
jenkins_gid=

# aws credentials
access_key=
secret_key=

# aws config
region=us-west-2

# create jenkins user and group
# add it to the docker group
groupadd -g${jenkins_gid} jenkins
useradd -d/var/lib/jenkins -s/bin/bash -u${jenkins_uid} -g${jenkins_gid} jenkins
usermod -aG docker jenkins

# TODO put it in the cbe
apt-get install gdb -y

# TODO do it on parent process ?
# TODO script the following steps

# gdb --pid 1
# b getgroups
# call setgroups(2,{497,999})
# call setuid(498)
# detach
# quit

# check docker is working
docker version
docker info

# authenticate to AWS ECR
aws configure set default.region ${region}
aws configure set aws_access_key_id ${access_key}
aws configure set aws_secret_access_key ${secret_key}
eval `aws ecr get-login`